#!/usr/bin/env node
/**
 * generate-ambient.js — Regenerate the shared-contract section of ofo-core-ambient.d.ts
 * from ofo-types.ts.
 *
 * Extracts every exported interface and type alias from ofo-types.ts and emits
 * them as pure ambient declarations (no import() expressions) so tsconfig.plugin.json
 * can consume them without ESM module support.
 *
 * Run automatically at the end of build-plugin.sh.
 * Do NOT hand-edit the generated section of ofo-core-ambient.d.ts.
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC_DIR = join(__dirname, 'src');
const typesPath = join(SRC_DIR, 'ofo-types.ts');
const outPath = join(SRC_DIR, 'ofo-core-ambient.d.ts');

const src = readFileSync(typesPath, 'utf8');
const lines = src.split('\n');
const ambientLines = [];

let mode = null;   // null | 'brace' | 'semi'
let braceDepth = 0;

for (const line of lines) {
  if (mode === null) {
    if (/^export interface /.test(line)) {
      ambientLines.push(line.replace(/^export /, 'declare '));
      braceDepth = (line.match(/{/g) || []).length - (line.match(/}/g) || []).length;
      mode = braceDepth > 0 ? 'brace' : null;
    } else if (/^export type /.test(line)) {
      ambientLines.push(line.replace(/^export /, 'declare '));
      // Single-line if ends with ; or is complete on this line
      if (/;\s*$/.test(line)) {
        ambientLines.push('');
      } else {
        mode = 'semi';
      }
    }
  } else if (mode === 'brace') {
    ambientLines.push(line);
    braceDepth += (line.match(/{/g) || []).length;
    braceDepth -= (line.match(/}/g) || []).length;
    if (braceDepth <= 0) {
      mode = null;
      ambientLines.push('');
    }
  } else if (mode === 'semi') {
    ambientLines.push(line);
    if (/;\s*$/.test(line)) {
      mode = null;
      ambientLines.push('');
    }
  }
}

const GENERATED_MARKER = '// --- Shared ofo action contract ---';
const existing = readFileSync(outPath, 'utf8');

// Keep everything before the generated marker (the hand-maintained OmniFocus augments)
const splitIdx = existing.indexOf(GENERATED_MARKER);
const runtimeSection = splitIdx >= 0 ? existing.slice(0, splitIdx).trimEnd() + '\n\n' : existing;

const generatedSection = [
  GENERATED_MARKER,
  '// AUTO-GENERATED by scripts/generate-ambient.js — DO NOT EDIT this section.',
  '// Source of truth: scripts/src/ofo-types.ts  |  Regenerated on every build.',
  '',
  ...ambientLines,
].join('\n').trimEnd() + '\n';

writeFileSync(outPath, runtimeSection + generatedSection, 'utf8');
console.log(`Written: ${outPath}`);
