// Ambient declarations for OmniFocus properties not in the 2021 type definitions.
// These exist at runtime in OmniFocus 4 and are used by ofo-core.ts.

interface Task {
  effectivelyCompleted: boolean;
  effectivelyDropped: boolean;
  plannedDate: Date | null;  // OF4 only; throws on unmigrated databases
  added: Date | null;
  clearTags(): void;
  markComplete(date?: Date | null): Task;
}

declare namespace Task {
  interface RepetitionRule {
    catchUpAutomatically: boolean;  // OF4 only; skips past dates on resolve
    scheduleType: any;              // Task.RepetitionScheduleType (Regularly | FromCompletion | None)
  }
}

interface Project {
  modified: Date | null;
  plannedDate: Date | null;  // OF4 only; throws on unmigrated databases
}

declare namespace Perspective {
  interface Custom {
    archivedFilterRules: any[];
    archivedTopLevelFilterAggregation: any;
  }
}

// Top-level OmniFocus document for tag hierarchy access
declare namespace Tag {
  const enum Status {
    Active = 0,
    OnHold = 1,
    Dropped = 2
  }
}

interface Tag {
  status: Tag.Status;
  children: Tag[];
  remainingTasks: Task[];
  removeTag(tag: Tag): void;
}

// Top-level tag hierarchy (from Database global)
declare const tags: Tag[];

// --- Shared ofo action contract ---
// AUTO-GENERATED by scripts/generate-ambient.js — DO NOT EDIT this section.
// Source of truth: scripts/src/ofo-types.ts  |  Regenerated on every build.

declare type OfoAction =
  | 'ofo-info'
  | 'ofo-complete'
  | 'ofo-create'
  | 'ofo-create-batch'
  | 'ofo-update'
  | 'ofo-search'
  | 'ofo-list'
  | 'ofo-tag'
  | 'ofo-tags'
  | 'ofo-perspective'
  | 'ofo-perspective-configure'
  | 'ofo-perspective-rules'
  | 'ofo-dump'
  | 'ofo-stats'
  | 'ofo-clarity'
  | 'ofo-stalled'
  | 'ofo-drop'
  | 'ofo-health';

declare interface OfoArgs {
  action: OfoAction;
  [key: string]: unknown;
}

declare interface OfoResult {
  success: boolean;
  error?: string;
  [key: string]: unknown;
}

declare interface OfoTask {
  id: string;
  name: string;
  project: string | null;
  tags: string[];
  flagged: boolean;
  completed: boolean;
  dueDate: Date | null;
  deferDate: Date | null;
  plannedDate: Date | null;
  completionDate: Date | null;
  estimatedMinutes: number | null;
  note: string | null;
  added: Date | null;
  modified: Date | null;
  repetitionRule: string | null;
  repetitionCatchUp: boolean | null;
  repetitionScheduleType: string | null;
  taskStatus: string;
}

declare interface OfoStats {
  inbox: number;
  overdue: number;
  flagged: number;
  dueToday: number;
  activeProjects: number;
  activeTasks: number;
  reviewOverdue: number;
  plannedToday: number;
  withEstimate: number;
}
